"""Application-wide constants. No magic numbers scattered in business logic."""

# Order statuses
ORDER_PENDING_PAYMENT = "PENDING_PAYMENT"
ORDER_PAYMENT_PROCESSING = "PAYMENT_PROCESSING"
ORDER_PAID = "PAID"
ORDER_FAILED = "FAILED"
ORDER_CANCELLED = "CANCELLED"
ORDER_REFUNDED = "REFUNDED"

ORDER_STATUS_CHOICES = [
    (ORDER_PENDING_PAYMENT, "Pending Payment"),
    (ORDER_PAYMENT_PROCESSING, "Payment Processing"),
    (ORDER_PAID, "Paid"),
    (ORDER_FAILED, "Failed"),
    (ORDER_CANCELLED, "Cancelled"),
    (ORDER_REFUNDED, "Refunded"),
]

ORDER_CANCELLABLE_STATUSES = {ORDER_PENDING_PAYMENT, ORDER_PAYMENT_PROCESSING}

# Payment methods
PAYMENT_METHOD_STRIPE = "STRIPE"
PAYMENT_METHOD_CRYPTO = "CRYPTO"
PAYMENT_METHOD_CHOICES = [
    (PAYMENT_METHOD_STRIPE, "Stripe"),
    (PAYMENT_METHOD_CRYPTO, "Crypto"),
]

# Payment transaction statuses
PAYMENT_INITIATED = "INITIATED"
PAYMENT_PROCESSING = "PROCESSING"
PAYMENT_COMPLETED = "COMPLETED"
PAYMENT_FAILED = "FAILED"
PAYMENT_CANCELLED = "CANCELLED"
PAYMENT_REFUNDED = "REFUNDED"

PAYMENT_STATUS_CHOICES = [
    (PAYMENT_INITIATED, "Initiated"),
    (PAYMENT_PROCESSING, "Processing"),
    (PAYMENT_COMPLETED, "Completed"),
    (PAYMENT_FAILED, "Failed"),
    (PAYMENT_CANCELLED, "Cancelled"),
    (PAYMENT_REFUNDED, "Refunded"),
]

# Valid payment state transitions: from_status -> set of allowed to_status
PAYMENT_TRANSITIONS = {
    PAYMENT_INITIATED: {PAYMENT_PROCESSING, PAYMENT_FAILED, PAYMENT_CANCELLED},
    PAYMENT_PROCESSING: {PAYMENT_COMPLETED, PAYMENT_FAILED},
    PAYMENT_COMPLETED: {PAYMENT_REFUNDED},
    PAYMENT_FAILED: set(),
    PAYMENT_CANCELLED: set(),
    PAYMENT_REFUNDED: set(),
}

# Agent roles
ROLE_SYSTEM = "system"
ROLE_USER = "user"
ROLE_ASSISTANT = "assistant"
ROLE_TOOL = "tool"
AGENT_ROLE_CHOICES = [
    (ROLE_SYSTEM, "System"),
    (ROLE_USER, "User"),
    (ROLE_ASSISTANT, "Assistant"),
    (ROLE_TOOL, "Tool"),
]

# Agent approval statuses
APPROVAL_PENDING = "PENDING"
APPROVAL_APPROVED = "APPROVED"
APPROVAL_REJECTED = "REJECTED"
APPROVAL_EXECUTED = "EXECUTED"
APPROVAL_FAILED = "FAILED"
APPROVAL_STATUS_CHOICES = [
    (APPROVAL_PENDING, "Pending"),
    (APPROVAL_APPROVED, "Approved"),
    (APPROVAL_REJECTED, "Rejected"),
    (APPROVAL_EXECUTED, "Executed"),
    (APPROVAL_FAILED, "Failed"),
]

AGENT_TOOL_CALL_SUCCESS = "SUCCESS"
AGENT_TOOL_CALL_FAILED = "FAILED"
AGENT_TOOL_CALL_STATUS_CHOICES = [
    (AGENT_TOOL_CALL_SUCCESS, "Success"),
    (AGENT_TOOL_CALL_FAILED, "Failed"),
]

CONVERSATION_OPEN = "OPEN"
CONVERSATION_CLOSED = "CLOSED"
CONVERSATION_STATUS_CHOICES = [
    (CONVERSATION_OPEN, "Open"),
    (CONVERSATION_CLOSED, "Closed"),
]
